name: amythos/lodash
author:
  name: null
  email: beyond.star@gmail.com
  url: null
copyright: 2015 null
description: 'A low-level utility library delivering consistency, customization, performance, and extra features.'
